# Network parameters
network_params:
  input_channel: 1
  output_channel: 256
  hidden_size: 256

# Image parameters
image_height: 64
image_width: 256
rgb: false
contrast_adjust: true
pad: true

# Training parameters
batch_size: 32
num_iter: 1000
val_interval: 5
workers: 10 
grad_clip: 5.0

# Dataset parameters
train_data: "model_train/train_data"
valid_data: "model_train/validation_set"
total_data_usage_ratio: 1.0
data_filtering_off: false
batch_max_length: 25

# Model architecture
transformation: "None"
feature_extraction: "VGG"
sequence_modeling: "BiLSTM"

# Optimization
optim: "adam"
lr: 1.0e-5
rho: 0.95
eps: 1.0e-8
weight_decay: 1.0e-4

# Model loading and saving
saved_model: "model_train/model_checkpoints/english_1.pth"
experiment_name: "train_5"
new_prediction: false
finetune: true

# Layer freezing
freeze_feature_extraction: true
freeze_sequence_modeling: false

# Character set and language
character: "0123456789!\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ €ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz"
lang_list: ["en"]