# Network parameters
network_params:
  input_channel: 1
  output_channel: 256
  hidden_size: 256

# Image parameters
image_height: 64
image_width: 256
rgb: false
contrast_adjust: false
pad: true

# Training parameters
batch_size: 32
num_iter: 10
val_interval: 2
workers: 2
grad_clip: 5.0

# Dataset parameters
train_data: "model_train/data/en_sample"
valid_data: "model_train/data/en_sample"
total_data_usage_ratio: 1.0
data_filtering_off: false
batch_max_length: 25

# Model architecture
transformation: "None"
feature_extraction: "VGG"
sequence_modeling: "BiLSTM"

# Optimization
optim: "adam"
lr: 1.0
rho: 0.95
eps: 1.0e-8

# Model loading and saving
saved_model: "model_train/model_checkpoints/english_g2.pth"
experiment_name: "test_finetune"
new_prediction: false
finetune: true

# Layer freezing
freeze_feature_extraction: true
freeze_sequence_modeling: false

# Character set and language
character: "0123456789!\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ €ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz"
lang_list: ["en"]